name: MaintenanceMode
version: 1.1
author: Rene Hampoelz
website: hampoelz.net

main: net.hampoelz.MaintenanceMode.Main.Main

commands:
  maintenance:
    usage: /maintenance [on/off/reload]
    description: Toggle the Maintenance Mode / Reload the config file
    aliases: [mm]
    
permissions:
  maintenancemode.*:
    children:
      maintenancemode.toggle: true
      maintenancemode.join: true
      maintenancemode.reload: true